#!/bin/sh

export GOPATH=$PWD/

# Make sure the dependencies are setup
# Import the script into this namespace
. ./configure

# Cleanup and format the code
# This will break on any syntax errors

echo "......................"
echo "Formatting the code .."
echo "......................"
echo ""
gofmt -s -w .

# Build the app

echo "......................"
echo "Building GGeoHash CLI."
echo "......................"
echo ""
rm -f ./bin/*
go build ./ggeohash/ggeohash_cli/cli.go && mv ./cli ./bin/ggeohash_cli
chmod -R 777 ./bin


echo "......................"
echo "Built Command Line Interface for GGeoHash"
echo "......................"
echo ""
ls ./bin/*
