#!/bin/sh

export GOPATH=$PWD/

echo "......................"
echo "Testing Go-GeoHash ..."
echo "......................"
echo ""

# Make sure the dependencies are setup
# Import the script into this namespace
. ./configure

# Make sure the app builds
. ./build

# Run the tests
# This will run the "all_spec_test.go" suite of tests
echo "......................"
echo "Running tests ........"
echo ""
echo "and .................."
echo ""
echo "Benchmarks ..........."
echo ""
echo "Please be patient while benchmarks run ..."
echo "5s/test * 14 tests --> A VERY LONG time ..."
echo ""
echo "......................"
echo ""

export GOMAXPROCS=1
go test -benchtime 5s -bench ".*" | tee test.log

echo '' >> test_benchmark.log
date >> test_benchmark.log
grep 'ns/op' test.log >> test_benchmark.log
