#!/bin/sh

GOPATH=$PWD/

echo "Testing Go-GeoHash ..."

# Make sure the dependencies are setup
./configure

# Cleanup and format the code
# This will break on any syntax errors
go fmt

# Run the tests
# This will run the "all_spec_test.go" suite of tests
go test 
